BUFF_SIZE = 1024

# default value used in id node
DEFAULT_ID = -1

# Bully's constants
MAX_TRANSMISSION_DELAY = 5
MAX_PROCESSING_DELAY = 2
TOTAL_DELAY = (2 * MAX_TRANSMISSION_DELAY) + MAX_PROCESSING_DELAY

LISTENING = 10

HEARTBEAT_TIME = 5
