version: "3.9"

networks:
  sdcc_net_1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.240.0/24
          gateway: 172.16.240.1

services:
  register_10:
    build: 
      context: ./
      dockerfile: register/Dockerfile
    stop_signal: SIGTERM
   # network_mode: "host" 
    networks:
      sdcc_net_1:
        ipv4_address: 172.16.240.2
    ports:
      - "8000:54350"
  
  node_60:
    build:
      context: ./
      dockerfile: node/Dockerfile
    stop_signal: SIGTERM
    #network_mode: "host"
    # deploy: 
    #   mode: replicated
    #   replicas: 4
    networks: 
      - sdcc_net_1
    ports:
      - 65126    
