version: "3.9"

services:
  register:
    hostname: register
    container_name: register
    build: 
      context: ./
      dockerfile: register/Dockerfile
    stdin_open: true # docker run -i
    tty: true        # docker run -t

  node:
    # hostname: node
    # container_name: node
    build:
      context: ./
      dockerfile: node/Dockerfile
    depends_on:
      - register
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    deploy: 
      mode: replicated
      replicas: 4